project_id = "pnhlgkoxsgxhiyesbtqh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.ai-chat]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false