// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://habnpuephuurcqkwblor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYm5wdWVwaHV1cmNxa3dibG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NDM4NzMsImV4cCI6MjA3ODQxOTg3M30.-56VyiVBHqlzFTjsx1SCbfWrB4P0wgUc19hO7BsNeZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});